project:
  type: website
  output-dir: docs

website:
  title: "Nipun Batra"
  navbar:
    right:
      - href: index.qmd
        text: Home


format:
  html:
    theme:
      light: [litera, styles.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto